Added init script

diff --git a/pypl b/pypl
--- a/pypl
+++ b/pypl
@@ -69,6 +69,7 @@ MP_CONFIG_DIR=~/.config/pyplate
 # User defined functions
 #---------------------------------------------------------------------
 
+##N- Pyplate
 
 # Create a directory if it does not exist
 mpCreateDir() {
@@ -204,13 +205,19 @@ DESC="Help tool for pyplate project"
 ##V logfile (uncomment to use logfile)
 #LOGFILE=${scriptPath}/${scriptName}.log
 
+##V Logging options (uncomment to activate logging parameters)
+#LOG_INFO=1
+#LOG_WARNING=1
+#LOG_ERROR=1
+#LOG_CRITICAL=1
+
 ##V Default command (uncomment to use a default command )
 DEFAULT=help
 
 ##V Pre script hook, execute this function before every command
 #PREHOOK=preCheck
 
-##V Post script hook, execute this function before every command
+##V Post script hook, execute this function after every command
 #POSTHOOK=
 
 ##V Function to be executed before every other cmd except DEFAULT function
@@ -218,6 +225,9 @@ DEFAULT=help
 
 ##V Function to be executed after every other function except DEFAULT function
 #POSTCMDHOOK=
+
+##V Function to be executed after information command
+#INFOHOOK=
 
 ##V Programs that are required to run the script (uncomment to use)
 #REQUIRED_PROGRAMS=(ls mv kalle)
@@ -255,82 +265,83 @@ bpCleanUp() { ##D Cleanup function
 bpExit() { ##D Function for safely exiting script
   bpCleanUp
 	
-	# execute postscript hook if existing
-	if [ -n "$POSTHOOK" ]; then
-    ${POSTHOOK}
-	fi
+  # execute postscript hook if existing
+  if [ -n "$POSTHOOK" ]; then
+     ${POSTHOOK}
+  fi
 	
   exit
 }
 
 bpErrorExit() {  ##D Safely exit script with a error 
-  echo -e "${BP_ERROR}${1}${E_END}"
+  #echo -e "${BP_C_ERROR}${1}${E_END}"
+  bpError "${1}"
   bpCleanUp
   exit
 }
 
 #--------------------------------------------------------------------- 
-# System functions and settings
+# Bashplate internal functions
 #---------------------------------------------------------------------
 
 # ANSI foreground colors codes
 #
 
-E_BLACK='\e[0;30m'        # Black 
-E_RED='\e[0;31m'          # Red
-E_GREEN='\e[0;32m'        # Green
-E_YELLOW='\e[0;33m'       # Yellow
-E_BLUE='\e[0;34m'         # Blue
-E_MAGENTA='\e[0;35m'      # Magenta
-E_CYAN='\e[0;36m'         # Cyan
-E_GRAY='\e[0;37m'         # Gray
-E_DARKGRAY='\e[1;30m'     # Dark Gray
-E_BR_RED='\e[1;31m'       # Bright Red
-E_BR_GREEN='\e[1;32m'     # Bright Green
-E_BR_YELLOW='\e[1;33m'    # Bright Yellow
-E_BR_BLUE='\e[1;34m'      # Bright Blue
-E_BR_MAGENTA='\e[1;35m'   # Bright Magenta
-E_BR_CYAN='\e[1;36m'      # Bright Cyan
-E_WHITE='\e[1;37m'        # White
+E_BLACK=$'\e[0;30m'        # Black 
+E_RED=$'\e[0;31m'          # Red
+E_GREEN=$'\e[0;32m'        # Green
+E_YELLOW=$'\e[0;33m'       # Yellow
+E_BLUE=$'\e[0;34m'         # Blue
+E_MAGENTA=$'\e[0;35m'      # Magenta
+E_CYAN=$'\e[0;36m'         # Cyan
+E_GRAY=$'\e[0;37m'         # Gray
+E_DARKGRAY=$'\e[1;30m'     # Dark Gray
+E_BR_RED=$'\e[1;31m'       # Bright Red
+E_BR_GREEN=$'\e[1;32m'     # Bright Green
+E_BR_YELLOW=$'\e[1;33m'    # Bright Yellow
+E_BR_BLUE=$'\e[1;34m'      # Bright Blue
+E_BR_MAGENTA=$'\e[1;35m'   # Bright Magenta
+E_BR_CYAN=$'\e[1;36m'      # Bright Cyan
+E_WHITE=$'\e[1;37m'        # White
 
 # ANSI background color codes
 #
-E_ON_BLACK='\e[40m'       # Black
-E_ON_RED='\e[41m'         # Red
-E_ON_GREEN='\e[42m'       # Green
-E_ON_YELLOW='\e[43m'      # Yellow
-E_ON_BLUE='\e[44m'        # Blue
-E_ON_MAGENTA='\e[45m'     # Magenta
-E_ON_CYAN='\e[46m'        # Cyan
-E_ON_WHITE='\e[47m'       # White
+E_ON_BLACK=$'\e[40m'       # Black
+E_ON_RED=$'\e[41m'         # Red
+E_ON_GREEN=$'\e[42m'       # Green
+E_ON_YELLOW=$'\e[43m'      # Yellow
+E_ON_BLUE=$'\e[44m'        # Blue
+E_ON_MAGENTA=$'\e[45m'     # Magenta
+E_ON_CYAN=$'\e[46m'        # Cyan
+E_ON_WHITE=$'\e[47m'       # White
 
 # ANSI Text attributes
-E_ATTR_BOLD='\e[1m'
-E_ATTR_LOWI='\e[2m' 
-E_ATTR_UNDERLINE='\e[4m'
-E_ATTR_BLINK='\e[5m'
-E_ATTR_REVERSE='\e[7m'
+E_ATTR_BOLD=$'\e[1m'
+E_ATTR_LOWI=$'\e[2m' 
+E_ATTR_UNDERLINE=$'\e[4m'
+E_ATTR_BLINK=$'\e[5m'
+E_ATTR_REVERSE=$'\e[7m'
 
 # ANSI cursor operations
 #
-E_RETURN="\e[F"           # Move cursor to begining of line
-E_UP="\e[A"               # Move cursor one line up
-E_DOWN="\e[B"             # Move cursor one line down
-E_FORWARD="\e[C"          # Move cursor forward
-E_BACK="\e[D"             # Move cursor backward
-E_HIDE="\e[?25l"          # Hide cursor 
-E_SHOW="\e[?25h"          # Show cursor 
+E_RETURN=$'\e[F'           # Move cursor to begining of line
+E_UP=$'\e[A'               # Move cursor one line up
+E_DOWN=$'\e[B'             # Move cursor one line down
+E_FORWARD=$'\e[C'          # Move cursor forward
+E_BACK=$'\e[D'             # Move cursor backward
+E_HIDE=$'\e[?25l'          # Hide cursor 
+E_SHOW=$'\e[?25h'          # Show cursor 
 
-E_END="\e[m"              # Clear Attributes
-
+E_END=$'\e[m'              # Clear Attributes
+ 
 # Internal bashplate colors
-BP_OK=$E_BR_GREEN
-BP_INFO=$E_BR_CYAN
-BP_WARNING=$E_BR_YELLOW
-BP_ERROR=$E_BR_RED
-BP_CRITICAL=$E_ON_RED$E_WHITE
-BP_LINE=$E_GREEN
-BP_LINE_TEXT=$E_BR_GREEN
+BP_C_OK=$E_BR_GREEN
+BP_C_INFO=$E_BR_CYAN
+BP_C_WARNING=$E_BR_YELLOW
+BP_C_ERROR=$E_BR_RED
+BP_C_CRITICAL=$E_ON_RED$E_WHITE
+BP_C_LINE=$E_GRAY
+BP_C_LINE_TEXT=$E_GRAY
 
 # Exit codes 
 #
@@ -347,12 +358,12 @@ BP_E_OK=0            # successful termination
 # arg5 line character
 bpPrintLineC() { ##D Print text with adjusted line after with selectable colors
   len1=${#1}
-	len4=${#4}
+  len4=${#4}
 	
-	echo -en ${2}${1}${4}${3}
-	l=$((${COLUMNS} - ${len1} - ${len4} - 3 ))
-	seq -s${5} ${l}|tr -d '[:digit:]'
-	echo -en ${E_END} 
+  echo -en ${2}${1}${4}${3}
+  l=$((${COLUMNS} - ${len1} - ${len4} - 3 ))
+  seq -s${5} ${l}|tr -d '[:digit:]'
+  echo -en ${E_END} 
 }
 
 # Print text with row
@@ -370,10 +381,10 @@ bpTextLine() { ##D Print text with line after
 
 # Print a divider row
 bpLine() { ##D Print a line  
-	bpPrintLineC "" "${E_GRAY}" "${E_GRAY}" "" "-" 
+  bpPrintLineC "" "${E_GRAY}" "${E_GRAY}" "" "-" 
 }
 
-# Legacy function
+# Legacy function (do not use in new applications)
 printLine() { 
   bpLine
 }
@@ -421,44 +432,71 @@ bpLog() { ##D Log to file command
 
 log() { ##C LOGFILE View logfile
   if [ -n "$LOGFILE" ]; then
-    D=$(sed -r -e "s|\[Info\]|\[\\${BP_INFO}Info\\${E_END}\]|"  \
-            -e "s|\[Warn\]|\[\\${BP_WARNING}Warn\\${E_END}\]|"  \
-            -e "s|\[Erro\]|\[\\${BP_ERROR}Erro\\${E_END}\]|"    \
+    if [ -f ${LOGFILE} ]; then  # Check that logfile exists
+	
+      D=$(sed -r -e "s|\[Info\]|\[\\${BP_C_INFO}Info\\${E_END}\]|"  \
+            -e "s|\[Warn\]|\[\\${BP_C_WARNING}Warn\\${E_END}\]|"  \
+            -e "s|\[Erro\]|\[\\${BP_C_ERROR}Erro\\${E_END}\]|"    \
             -e "s/[-0-9]+/\\${E_GREEN}&\\${E_END}/1"            \
             -e "s/[:0-9]+/\\${E_BR_GREEN}&\\${E_END}/6"            \
             -e "s|\[Crit\]|\[\\${E_ON_RED}\\${E_WHITE}Crit\\${E_END}\]|" < "${LOGFILE}" ) 
 
-    echo -e "$D"
+      echo -e "$D"
+    fi
   else
     bpInfo "Logging is not activated"
     exit
   fi
 }
 
+mlog() {   ##C LOGFILE Monitor logfile
+  if [ -n "$LOGFILE" ]; then
+    if [ -f ${LOGFILE} ]; then  # Check that logfile exists
+      tail -f ${LOGFILE} | sed -r -e "s|\[Info\]|\[\\${BP_C_INFO}Info\\${E_END}\]|"  \
+            -e "s|\[Warn\]|\[\\${BP_C_WARNING}Warn\\${E_END}\]|"  \
+            -e "s|\[Erro\]|\[\\${BP_C_ERROR}Erro\\${E_END}\]|"    \
+            -e "s/[-0-9]+/\\${E_GREEN}&\\${E_END}/1"            \
+            -e "s/[:0-9]+/\\${E_BR_GREEN}&\\${E_END}/6"            \
+            -e "s|\[Crit\]|\[\\${E_ON_RED}\\${E_WHITE}Crit\\${E_END}\]|" 
+
+		fi
+  else
+    bpInfo "Logging is not activated"
+    exit
+  fi
+}
 
 bpOk() { ##D Success message 
-  bpLog "[Ok] $1"
-  echo -e "[${BP_OK}Ok${E_END}] $1"
+  bpLog "[ Ok ] $1"
+  echo -e "[${BP_C_OK}Ok${E_END}] $1"
 }
 
 bpInfo() { ##D Info message 
-  bpLog "[Info] $1"
-  echo -e "[${BP_INFO}Info${E_END}] $1"
+  if [ -n "$LOG_INFO" ]; then
+    bpLog "[Info] $1"
+  fi
+  echo -e "[${BP_C_INFO}Info${E_END}] $1"
 }
 
 bpWarning() { ##D Warning message
-  bpLog "[Warn] $1"
-  echo -e "[${BP_WARNING}Warning${E_END}] $1"
+  if [ -n "$LOG_WARNING" ]; then	
+    bpLog "[Warn] $1"
+  fi
+  echo -e "[${BP_C_WARNING}Warning${E_END}] $1"
 }
 
 bpError() { ##D Error message
-  bpLog "[Erro] $1"
-  echo -e "[${BP_ERROR}Error${E_END}] $1"
+  if [ -n "$LOG_ERROR" ]; then
+    bpLog "[Erro] $1"  
+  fi
+  echo -e "[${BP_C_ERROR}Error${E_END}] $1"
 }
 
 bpCritical() { ##D Critical error message
-  bpLog "[Crit] $1"
-  echo -e "[${BP_CRITICAL}Critical${E_END}] $1"
+  if [ -n "$LOG_CRITICAL" ]; then
+    bpLog "[Crit] $1"
+  fi
+  echo -e "[${BP_C_CRITICAL}Critical${E_END}] $1"
   bpExit
 }
 
@@ -473,7 +511,8 @@ assertRoot() { ##D Assert that user is root
 assertNoLockFile() { ##D Assert that lockfile is not present
   if [ -n "$LOCK_FILE" ]; then 
     if [ -f "$LOCK_FILE" ]; then
-      echo -e "${BP_ERROR}Script is already running. (${LOCK_FILE})${E_END} "
+      #echo -e "${BP_C_ERROR}Script is already running. (${LOCK_FILE})${E_END} "
+      bpError "Script is already running. (${LOCK_FILE})"
       exit  # do not use bpExit because lock belongs to other process
     fi
     touch "$LOCK_FILE"              
@@ -484,12 +523,14 @@ assertRequiredProgs() { ##D Assert that required programs are available on the s
   if [ -n "${REQUIRED_PROGRAMS}" ]; then
     for p in ${REQUIRED_PROGRAMS[@]}; do
       hash "$p" 2>&- || \
-      { echo -e >&2 "${BP_ERROR}Required program \"$p\" not found.${E_END}"; exit 1; }
+        { bpError "Required program \"$p\" not found."; exit 1; }
+#      { echo -e >&2 "${BP_C_ERROR}Required program \"$p\" not found.${E_END}"; exit 1; }
     done
   fi
 }
 
 info() { ##D Show information about script
+  bpTextLine "Script information"
   printVar scriptName      "Script name" 
   printVar scriptPath      "Script path" 
   printVar VERSION         "Script version" 
@@ -500,7 +541,12 @@ info() { ##D Show information about script
   printVar "REQUIRED_PROGRAMS" "Dependencies"
   printInfo "PID" $$  
   printVar DATE "Date" 
-  printVar TIME "Time" 
+  printVar TIME "Time"
+	
+  if [ -n "${INFOHOOK}" ]; then
+    bpTextLine "App. information"
+    ${INFOHOOK}
+  fi
 }
 
 check() { ##D Make a shellcheck
@@ -518,6 +564,16 @@ chSetting() {
   VAL="$3"
   sed -i "s/^\(${SETTING}\s*=\s*\).*\$/\1$VAL/" "$1"
 }
+
+# Replace text in file
+#
+# arg1 file 
+# arg2 text to replace
+# arg3 new text
+bpReplace() {  ##D Replace text in file
+  sed -i -e "s/${2}/${3}/g"  $1
+}
+	 
 
 printCommand() { 
   help_line=$1
@@ -547,22 +603,18 @@ printCondLine() {
 }
 
 printNamedLine() {
-  #name=$(echo "$1" | sed -s 's/^.*##N-//' | awk '{print $1}')
-	name=$(echo "$1" | sed -e 's/^.*##N-//' -e 's/^[ \t]*//' )
-	bpTextLineC $name "${E_BLUE}" "${E_GREEN}"
+  name=$(echo "$1" | sed -e 's/^.*##N-//' -e 's/^[ \t]*//' )
+  bpTextLine "$name"
 }
-
 
 
 printCondNamedLine() {
   help_line=$1
   C=$(echo "$1" | sed -s 's/^.*##CN-//' | awk '{print $1}')
-	#name=$(echo "$1" | sed -s 's/^.*##CN-//' | awk '{print $2}')
 	name=$(echo "$help_line" | sed -e 's/^.*'"$C"'//' -e 's/^[ \t]*//' )
   eval "D=\$$C"
   if [ -n "$D" ]; then
-		 #bpTextLineC $name "${E_BLUE}" "${E_GREEN}"
-		 bpTextLine "$name" 
+    bpTextLine "$name"
   fi
 }
 
@@ -570,17 +622,18 @@ help() { ## Print this help information
   echo "$USAGE"
   echo -e "$DESC"
   echo 
-  printf "%-20s  %s\n" "Command" "Help"
-  printLine
+#  printf "%-20s  %s\n" "Command" "Help"
+#  printLine
   IFS=$'\n'
   SC=$1
-  help_lines=$(grep -h '##' "$0" | grep -v grep | grep -v '##D' | grep -v '##V' | grep -v '\*##C' | grep -v '\*##C-' |  grep -v '\"##' |  grep -v '##N-//' | grep -v help_line | grep -v printLine)
+  #help_lines=$(grep -h '##' "$0" | grep -v grep | grep -v '##D' | grep -v '##V' | grep -v '\*##C' | grep -v '\*##C-' |  grep -v '\"##' |  grep -v '##N-//' | grep -v help_line | grep -v printLine)
+  help_lines=$(grep -h '##' "$0" | grep -v -e 'grep' -e '##D' -e '##V' -e '\*##C' -e '\*##C-' -e '\"##' -e '##N-//' -e 'help_line' -e   'printLine')
   for help_line in ${help_lines[@]} ; do
     case "$help_line" in
       *"##-"*)   printLine ;;
-			*"##C-"*)  printCondLine       "$help_line" ;;
-			*"##N-"*)  printNamedLine      "$help_line" ;;
-			*"##CN-"*) printCondNamedLine  "$help_line" ;;
+      *"##C-"*)  printCondLine       "$help_line" ;;
+      *"##N-"*)  printNamedLine      "$help_line" ;;
+      *"##CN-"*) printCondNamedLine  "$help_line" ;;
       *"##C"*)   printCondCommand    "$help_line" ;;
       *"##"*)    printCommand        "$help_line" '##' ;;
       *)    
@@ -596,9 +649,8 @@ ihelp() { ##D Print internal help information
   help_lines=$(grep -h '##' "$0" | grep -v grep | grep -v '\*"##[ A-Z]"\*' | grep -v help_line | grep -v printLine)
   for help_line in ${help_lines[@]}; do
     case "$help_line" in
-      "##-") printLine ;;
-      *"##D"*) 
-          printCommand "$help_line" '##D' ;;
+      "##-")   printLine ;;
+      *"##D"*) printCommand "$help_line" '##D' ;;
       *)    
       ;;   
     esac
@@ -664,7 +716,7 @@ runCommand() {
       # execute command
       ${command} "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9" "${10}"
       
-			# execute post command hook  if existing
+      # execute post command hook  if existing
       if [ -n "$POSTCMDHOOK" ]; then
         ${POSTCMDHOOK}
       fi      
@@ -674,7 +726,7 @@ runCommand() {
   bpErrorExit "Command \"$1\" not found"	 
 }
 
-# Init 
+# Init magic variables
 #
 DATE=$(date +"%Y-%m-%d")
 TIME=$(date +"%H:%M:%S")
@@ -698,6 +750,5 @@ runCommand "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9" "${10}"
 
 # Exit cleanly
 bpExit
-
 
 ##-
